### ISSUE TITLE
Can not create a new color in _theme-colors.styl

### ISSUE THREAD

**Issue by Liruwei** [willianjusten/cards-jekyll-template#10]
i add the 'ios' color but no work and the tag’s border disappears
~~~
themes = {
    post-jekyll: #B31917,
    post-css: #2DA0C3,
    post-js: #D6BA32,
    post-html: #EB7728,
    post-svg: #7D669E,
    post-dev: #637a91,
    post-misc: #7AAB13,
    post-ios: #7AAB13
}
~~~

![](http://ww4.sinaimg.cn/large/962a6dfegw1f5dsr0immgj209t08i0td.jpg)

**Comment by willianjusten** [comment]
Hi @Liruwei , did you ran `gulp` after created the theme?
Everything looks perfect here.

![screen shot 2016-06-30 at 3 22 18 pm](https://cloud.githubusercontent.com/assets/3991845/16499403/b85bb278-3ed6-11e6-803a-18fde6893091.png)

**Comment by Liruwei** [comment]
thanks @willianjusten ，i had  `gulp`  but it dosn't work and throw that 
![](http://ww3.sinaimg.cn/large/962a6dfegw1f5e7xj3ze9j21c80tadnr.jpg)

**Comment by Liruwei** [comment]
@willianjusten  😂～～thanks～

**Comment by willianjusten** [comment]
xD

**Comment by djKooks** [comment]
@Liruwei @willianjusten I'm also facing with same problem with '@import "jeet"' now. How did you solved it?

**Comment by willianjusten** [comment]
First of all, install deps using `npm install`.

**Comment by djKooks** [comment]
@willianjusten Yes, I setup with `npm install` and tried `gulp` but see problem like below.

```
[13:07:07] Plumber found unhandled error:
 Error in plugin 'gulp-stylus'
Message:
    /Users/kwangin/workspace/djkooks.github.com/src/styl/main.styl:22:9
   18|     And of course, look in node_modules for axis-css and jeet
   19| */
   20| 
   21| @import "kouto-swiss"
   22| @import "jeet"
---------------^
```

**Comment by Liruwei** [comment]
@djKooks run npm install jeet@6.1.1 --save-dev in project

**Comment by djKooks** [comment]
@Liruwei Thanks~now my change works well.

**Comment by willianjusten** [comment]
Weird... `npm install` should be working... I'll verify this with a clean clone...

**Comment by noxidsoft** [comment]
I have this issue, even after running `npm install jeet@6.1.4 --save-dev`, my output is:

Noels-MBP:17.0 noxidsoft$ gulp
[15:48:56] Using gulpfile /Applications/MAMP/htdocs/dev_noxidsoft_flat/17.0/gulpfile.js
[15:48:56] Starting 'js'...
[15:48:56] Starting 'stylus'...
[15:48:56] Finished 'stylus' after 4.52 ms
[15:48:56] Starting 'jekyll-build'...
[15:48:56] Starting 'watch'...
Configuration file: /Applications/MAMP/htdocs/dev_noxidsoft_flat/17.0/_config.yml
            Source: /Applications/MAMP/htdocs/dev_noxidsoft_flat/17.0
       Destination: /Applications/MAMP/htdocs/dev_noxidsoft_flat/17.0/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
[15:48:57] Finished 'watch' after 1.44 s
[15:48:57] Plumber found unhandled error:
 Error in plugin 'gulp-stylus'
Message:
    /Applications/MAMP/htdocs/dev_noxidsoft_flat/17.0/src/styl/main.styl:22:9
   18|     And of course, look in node_modules for axis-css and jeet
   19| */
   20| 
   21| @import "kouto-swiss"
   22| @import "jeet"
---------------^
   23| normalize()
   24| @import "_variables"
   25| @import "_typo"

failed to locate @import file jeet.styl

Details:
    lineno: 22
    column: 9
    filename: /Applications/MAMP/htdocs/dev_noxidsoft_flat/17.0/src/styl/main.styl
    stylusStack: 
    input: /*  Syntax Quick Reference for Jeet
    --------------------------
    column(ratios = 1, offset = 0, cycle = 0, uncycle = 0, gutter = jeet.gutter)
    span(ratio = 1, offset = 0)
    shift(ratios = 0, col_or_span = column, gutter = jeet.gutter)
    unshift()
    edit()
    center(max_width = 1410px, pad = 0)
    stack(pad = 0, align = false)
    unstack()
    align(direction = both)
    cf()

    For more info see:
        Kouto Swiss Doc: http://kouto-swiss.io/
        Jeet Doc: http://jeet.gs

    And of course, look in node_modules for axis-css and jeet
*/

@import "kouto-swiss"
@import "jeet"
normalize()
@import "_variables"
@import "_typo"
@import "_icons"
@import "_menu"
@import "_search"
@import "_elements"
@import "_header"
@import "_home"
@import "_post"
@import "_share"
@import "_hightlight"
@import "_author"
@import "_footer"
@import "_theme-colors"
                    done in 0.644 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
[15:48:58] Finished 'jekyll-build' after 2.29 s
[15:48:58] Starting 'jekyll-rebuild'...
[15:48:58] Finished 'jekyll-rebuild' after 39 μs
[15:48:58] Starting 'browser-sync'...
[15:48:58] Finished 'browser-sync' after 85 ms
[15:48:58] Finished 'js' after 2.4 s
[15:48:58] Starting 'default'...
[15:48:58] Finished 'default' after 6.76 μs
[BS] Local URL: http://localhost:3000
[BS] External URL: http://10.0.0.127:3000
[BS] Serving files from: _site

**Comment by djKooks** [comment]
@noxidsoft I also tested, and still 6.1.1 only works.

**Comment by willianjusten** [comment]
I updated this yesterday and it works without any problem...Delete your old node_modules and try to install again. And please @noxidsoft , you don't need to create another issue for the same problem...
