### ISSUE TITLE
Header content doesn't update via Gulp

### ISSUE THREAD

**Issue by noxidsoft** [willianjusten/cards-jekyll-template#12]
Changing the _header.styl title content values and then trying to compile with Gulp throws a stylus error. I made sure that gulp-stylus was on current 2.5.0 version. Any help appreciated.

$Noels-MBP:17.0 noxidsoft$ gulp
[15:48:56] Using gulpfile /Applications/MAMP/htdocs/dev_noxidsoft_flat/17.0/gulpfile.js
[15:48:56] Starting 'js'...
[15:48:56] Starting 'stylus'...
[15:48:56] Finished 'stylus' after 4.52 ms
[15:48:56] Starting 'jekyll-build'...
[15:48:56] Starting 'watch'...
Configuration file: /Applications/MAMP/htdocs/dev_noxidsoft_flat/17.0/_config.yml
            Source: /Applications/MAMP/htdocs/dev_noxidsoft_flat/17.0
       Destination: /Applications/MAMP/htdocs/dev_noxidsoft_flat/17.0/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
[15:48:57] Finished 'watch' after 1.44 s
[15:48:57] Plumber found unhandled error:
 Error in plugin 'gulp-stylus'
Message:
    /Applications/MAMP/htdocs/dev_noxidsoft_flat/17.0/src/styl/main.styl:22:9
   18|     And of course, look in node_modules for axis-css and jeet
   19| */
   20| 
   21| @import "kouto-swiss"
   22| @import "jeet"
---------------^
   23| normalize()
   24| @import "_variables"
   25| @import "_typo"

failed to locate @import file jeet.styl

Details:
    lineno: 22
    column: 9
    filename: /Applications/MAMP/htdocs/dev_noxidsoft_flat/17.0/src/styl/main.styl
    stylusStack: 
    input: /*  Syntax Quick Reference for Jeet
    --------------------------
    column(ratios = 1, offset = 0, cycle = 0, uncycle = 0, gutter = jeet.gutter)
    span(ratio = 1, offset = 0)
    shift(ratios = 0, col_or_span = column, gutter = jeet.gutter)
    unshift()
    edit()
    center(max_width = 1410px, pad = 0)
    stack(pad = 0, align = false)
    unstack()
    align(direction = both)
    cf()
...

**Comment by willianjusten** [comment]
C'mon guy, it's the same error as before. You have to update the `jeet` dependency as I said.
Merge my last update and run `npm install`.

**Comment by noxidsoft** [comment]
Hi W, many apologies, I just thought as this was a different repo, was just trying to be helpful.

https://github.com/willianjusten/will-jekyll-template
https://github.com/willianjusten/cards-jekyll-template

Love you work, you are one of the few able to get server requests down to just 3, impressive. One of the main reasons I am aiming to get your template working consistently out-of-the-box. Keep up the great work. Kudos.

**Comment by willianjusten** [comment]
I'm sorry @noxidsoft, today wasn't a good day to me... I'm very very sorry for my attitude...

**Comment by willianjusten** [comment]
Its working now?

**Comment by noxidsoft** [comment]
Completely understand, lol, coder rage, I hear you bro (:

https://github.com/willianjusten/cards-jekyll-template

I did some more exploration because I still couldn't get the header to update from _header.styl.

(I did most of the following on my Windows 10 machine, yet to see if it replicates on the Mac lappy)
What I found I had to do was change gulpfile.js line 25 from... 
`return cp.spawn('jekyll', ['build'], {stdio: 'inherit'})`
to
`return cp.spawn('jekyll.bat', ['build'], {stdio: 'inherit'})`

I made sure I was patched to latest Jeet, cause I keep getting this on command line:
`   18|     And of course, look in node_modules for axis-css and jeet
   19| */
   20|
   21| @import "kouto-swiss"
   22| @import "jeet"
---------------^
   23| normalize()
   24| @import "_variables"
   25| @import "_typo"

failed to locate @import file jeet.styl

Details:
    lineno: 22
    column: 9
    filename: C:\xampp\htdocs\churchalerts\1.0\src\styl\main.styl
    stylusStack:
    input: /*  Syntax Quick Reference for Jeet
    --------------------------
    column(ratios = 1, offset = 0, cycle = 0, uncycle = 0, gutter = jeet.gutter)`

I ended up working out that it was as it said, failing to import jeet.styl (I have never used Jeet before, I'm a recent Suzy man and old/cold CSS dinosaur, hehe).

So I found through some re(G)search that Jeet has a long history of sketchy alias issues, to be fair I understand the coders pain of keeping all the pieces in a row and staying sane. But it appears this is still holding true for Jeet@6.1.4 and there is a promise that Jeet@6.2.x might be better long term.

Anyway, I changed the main.styl file on line 22 to a traditional...
`@import "jeet/_jeet.styl"`
from just...
`@import "jeet"`

This now fixed the header (overall stylus) compile issue and it appears that Jeet is doing it's job. But, it broke parts of the template.

![image](https://cloud.githubusercontent.com/assets/729135/17098057/b62283a2-52a3-11e6-9786-0f52cbde455c.png)

Hahahaha, love it, this is why I do this, always keeps me on my toes. Any help with getting the template back on track would be great?

I will fork the repo and make adjustments there, do you mind if I tinker and continue to test?

**Comment by noxidsoft** [comment]
Yep, can confirm that Mac requires qualifying the Jeet import ref too. Breaks the template the same way.

**Comment by noxidsoft** [comment]
The menu is a bit off too. Someone else that has more experience with Jeet may have a better go at it rather than me, newbie alert.

**Comment by willianjusten** [comment]
About Windows Setup, I fixed this on my last commit, you don't have to change anymore and will run on Mac or Windows without a problem.

About those errors, it is very weird...I really don't know what is going on...=/

Can you inspect the footer and show me the styles?

**Comment by noxidsoft** [comment]
It might be to do with the fact I was downloading via this link, it might need updating:
http://jekyllthemes.org/themes/cards-jekyll-template/

I'll try a fresh pull from the current repo release and come back to you.

**Comment by willianjusten** [comment]
Try `git clone` from here... maybe it's better.

**Comment by noxidsoft** [comment]
I cloned the repo, still need to change the jeet reference and change to jekyll.bat on Windows 10.

Style for footer is as follows:
![image](https://cloud.githubusercontent.com/assets/729135/17128817/bd66b0c0-5352-11e6-834c-1b97fcc1e45f.png)

**Comment by noxidsoft** [comment]
The ribbon:
```
.ribbon {
    position: absolute;
    right: -5px;
    top: -5px;
    z-index: 1;
    overflow: hidden;
    width: 75px;
    height: 75px;
    text-align: right;
}
```

It can be centred again by changing to:
```
text-align: center;
```

**Comment by noxidsoft** [comment]
The footer:
```
footer p, footer a {
    text-decoration: none;
    font-family: 'Open Sans',sans-serif;
    font-weight: 300;
    font-style: normal;
    color: #fff;
    text-align: j-center;
    margin: 0;
}
```
The j-center comes up as invalid css, so changing to the following fixes:
```
text-align: center;
```
Is j-center a mix-in that is getting through without conversion? Might be a Jeet/Stylus bug?

**Comment by noxidsoft** [comment]
The menu has the same j-center Jeet bug. I just added some left padding (_menu.styl - line 56):
```
margin 0 1em rem(10px)
```

**Comment by willianjusten** [comment]
Weird...I'm running a clean project here without those errors...I don't know why you get this, but seems you know what is now right?

Can I close this issue?

**Comment by noxidsoft** [comment]
Yes please.

**Comment by willianjusten** [comment]
I'm sorry for this trouble, I'll try to run this project another time later with different versions of OS and Jeet, maybe I can fix...

**Comment by noxidsoft** [comment]
Thank you Willian, I can still use the theme though. And thanks for your skill, I can learn a lot from what you have done here in your use of Gulp and other node toolsets. I'm a Joomla/Wordpress guy normally, so I will be using your techniques for templates I build for those CMS's. Stay strong.

**Comment by willianjusten** [comment]
I created a Jekyll course, it is in brazilian portuguese, but if you want to [take a look](http://willianjusten.teachable.com/courses/criando-sites-estaticos-com-jekyll/).
