### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by iamquan** [willianjusten/cards-jekyll-template#16]
Hi

When I open the demo and Chrome console, then I scroll down it shows error: 'Uncaught TypeError: Cannot read property 'style' of null'. I also check on your blog: https://willianjusten.com.br/, this error also happens.

**Comment by willianjusten** [comment]
Ops, you're right! This is because I don't have the header at my home, I'll fix that right now, thanks! =D

**Comment by iamquan** [comment]
Yeah, just recompile it.

**Comment by willianjusten** [comment]
Fixed in my blog and here =D
