### ISSUE TITLE
Cards scrolling and positioning issue

### ISSUE THREAD

**Issue by ymedaghri** [willianjusten/cards-jekyll-template#26]
Hi Willian, Great template by the way.
I am facing an issue with the positionning of the cards.
I used npm & gulp install commands you described but the scrolling does not work at all neither the positioning.
When I have access to you website everything is fine but with the github one I get the result in attachement.
Do you have any clue about that ?
Thank you,
Youssef
![cardslayout](https://user-images.githubusercontent.com/28937236/26974305-0235b6fc-4d1b-11e7-9b05-34dd7e021168.png)

**Comment by ymedaghri** [comment]
No matter, when I forked the repo it worked great

**Comment by willianjusten** [comment]
So weird, did you fork which repo? This one or mine?
Another person told me about this issue, but I didn't get time to analyse yet...

**Comment by ymedaghri** [comment]
Hi Willian,
I figured it out, the issue is on master branch vs gh-pages branch.
If you check out master branch the two filed below have some differences with gh-pages branch
	modified:   assets/css/main.css
	modified:   assets/js/main.js

So if you try to install from master branch by using for example the baseurl "", you have this issue.
Whereas if you do the same on gh-pages branch, everything is fine.

I could not look at the differences because the files having differences are minified.
That's it.

I have another question, please.
Could you tell me what kind of library you use for the infinite scrolling of the cards on your site ?

Thank you,

Best Regards,

**Comment by willianjusten** [comment]
Oh thanks for coming with this answer! 
I'll update there to have everything working as expected.

And I don't use infinite scrolling on my site, it's exactly the same as this template =o

**Comment by JamesSkemp** [comment]
Hi Youssef.

I'm experiencing the same issue, but using your suggestion of copying files from gh_pages doesn't seem to be working. Did you end up cloning gh_pages, or using master and updating the main.css and main.js file?

**Comment by ymedaghri** [comment]
Hi,

I made a new clone of gh-pages.

Best Regards

**Comment by JamesSkemp** [comment]
Thanks!

And it looks like the issue is the enhancement from issue #19. Removing the 'post' class seems to resolve the issue.

**Comment by willianjusten** [comment]
I'm sorry for those things guys, I didn't test properly everything. I'll analyse everything and fix those issues.

**Comment by willianjusten** [comment]
As @JamesSkemp said, this issue was introduced by #19, I fixed that and syncronized both master and gh-pages. Everything is fine now.
