### ISSUE TITLE
Question: Homepage cards pushed down resulting in blank space

### ISSUE THREAD

**Issue by JamesSkemp** [willianjusten/cards-jekyll-template#27]
I'm running into issues after pulling down a copy of the this theme where the homepage loads the initial posts (I'm just using an exact copy of this repo) but they're all pushed down below the fold.

This results in the title, menu, and search being where they should be, but they're followed by blank space.

Then I see two rows of posts, the footer, and then the last row of posts. The series and tags pages work as expected, and the empty space on the homepage seems to be close to the height of the block that would be there if it was one of those subpages.

I've tried dropping in the default CSS and it results in the exact same behavior. Pulling up https://willianjusten.com.br/cards-jekyll-template/ results in the site working as expected, so it doesn't appear to be an issue (Chrome current on Mac).

I've tried inspecting CSS and things appear to be matching up.

Any suggestions on how I could try resolving this?

Example: http://ebacher-skemp.com/

**Comment by willianjusten** [comment]
Hi @JamesSkemp , another person told me about this issue, I didn't have time to analyze yet. I'll try to take a look today and see what can I do and I'll come here with the answer =)

**Comment by willianjusten** [comment]
Oh, he found the issue, it's described here in #26 .

**Comment by JamesSkemp** [comment]
I'm sorry, no idea how I missed that issue; I would have thought I would have checked before posting mine. :(
