### ISSUE TITLE
How to change the post grid to rectangles instead of squares?

### ISSUE THREAD

**Issue by algorithmor** [willianjusten/cards-jekyll-template#30]
Hi Willian,

First, I would like to thank you for creating such a beautiful and really amazing template. Its makes the endeavour to start a Jekyll blog super easy. Kudos!! 

Now, for my question. I would like to change the grid to display rectangles, instead of squares and also the grid to show from left edge to right edge instead of leaving a very wide border. Can you please tell if this is configurable? If yes, then it would be a great help. 

Thanks,
Ash

**Comment by willianjusten** [comment]
Hello @algorithmor , there's no option to configure that, but you can easily change the size and paddings/margins on this [file](https://github.com/willianjusten/cards-jekyll-template/blob/gh-pages/src/styl/_home.styl)

Edit the [L5](https://github.com/willianjusten/cards-jekyll-template/blob/gh-pages/src/styl/_home.styl#L5) to remove the centered border and the [L19](https://github.com/willianjusten/cards-jekyll-template/blob/gh-pages/src/styl/_home.styl#L19) to change the size of the card.

**Comment by aishydevil12286** [comment]
Thanks Willian for the response. I figured it out after some hit and trial. Great work again by the way. Made my life a whole lot easier. :)

**Comment by willianjusten** [comment]
Great, so I'll close here =)
