### ISSUE TITLE
Help with the logo in Mobile view

### ISSUE THREAD

**Issue by aishydevil12286** [willianjusten/cards-jekyll-template#34]
Hi Will,

Sorry for the noob question. I am looking to use an SVG graphic file as the logo. So, I have two questions. 

1. How to configure the Blog and title to use a logo
2. The original SVG is pretty big. How do I ensure that it will scale appropriately based on the size of the window.

**Comment by willianjusten** [comment]
Hum...all you have to do is remove the styles for logo [here](https://github.com/willianjusten/cards-jekyll-template/blob/gh-pages/src/styl/_header.styl#L30)

And you'll need to create some styles to the logo, as a container with a defined `max-width`.

**Comment by aishydevil12286** [comment]
Thanks !! Will give that a try.
