### ISSUE TITLE
How to add disqus comments?

### ISSUE THREAD

**Issue by aishydevil12286** [willianjusten/cards-jekyll-template#37]
Hi Willian,

I would like to add disqus support to my blog. I am reading the steps and it says that i need to add 
comments: true to YAML frontmatter and so I did the same in page.html

---
layout: default
comments: true
---

After this the second step is to

<2> 

In between a {% if page.comments %} and a {% endif %} tag, copy and paste the Universal Embed Code in the appropriate template where you'd like Disqus to load.

Now, do I ad the Embed code in page.html or in default.html as i do see similar tag logic in default.html but not in page.html

**Comment by aishydevil12286** [comment]
I found that disqus is already configured through comments.html. Will give that a try. Awesome theme man!!

**Comment by algorithmor** [comment]
Resolved it. All I had to do was add my disqus shortname in _config.yml
disqus_username:  <disqus shortname>

and then have comments:true in the post

**Comment by aishydevil12286** [comment]
Resolved it. All I had to do was add my disqus shortname in _config.yml
disqus_username:

and then have comments:true in the post
