### ISSUE TITLE
What would be the best way to add Google Analytics using this theme?

### ISSUE THREAD

**Issue by aishydevil12286** [willianjusten/cards-jekyll-template#38]
Hi Willian,

I plan on using Google Analytics with my Jekyll site. I found that currently there is no support in the theme for that. Can you suggest what would be the best way to add google analytics to the template.

Thanks!

**Comment by willianjusten** [comment]
Hey @aishydevil12286 , all you have to do is create an `analytics.js` file on `src/js` and run gulp. It will add the analytics to your `main.js` and it will work =)

**Comment by willianjusten** [comment]
You can take a look at my [own blog](https://github.com/willianjusten/willianjusten.github.io/blob/master/gulpfile.js#L65), I added a `-p` parameter to use this `analytics` only on production.

**Comment by aishydevil12286** [comment]
Thanks for the quick response Willian. I will use the same.
