### ISSUE TITLE
Liquid Exception: undefined method `gsub' for 300:Fixnum in index.html

### ISSUE THREAD

**Issue by algui91** [willianjusten/cards-jekyll-template#6]
Hi, Great template. When I try to use it on my posts, I am getting 

    Liquid Exception: undefined method `gsub' for 300:Fixnum in index.html

Any idea of what it could be?

I've been searching but found nothing

Regards

**Comment by algui91** [comment]
I Finally found the error, some of my posts have a tag with a number, like

- 300
- 404

That is what was causing the error.

**Comment by willianjusten** [comment]
If you want a page for 404 or 300, you should create as Pages, not as Post. But Jekyll handle posts with number, that's not the problem...

Take a look at this [example page with number](http://willianjusten.com.br/dica-rapida-1/)

**Comment by algui91** [comment]
No,  that wasn't the problem. The problem is that I had a post with a tag
400, not related with the http status.

On Mon, Jun 6, 2016, 02:24 Willian Justen <notifications@github.com> wrote:

> Closed #6
> <https://github.com/willianjusten/cards-jekyll-template/issues/6>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/willianjusten/cards-jekyll-template/issues/6#event-682295857>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAYGLQDMXnAOki5HQByxAKNaBpP_GBrdks5qI2jIgaJpZM4IudfZ>
> .
>
-- 

Alejandro Alcalde - elbauldelprogramador.com
