### ISSUE TITLE
gulp: command not found

### ISSUE THREAD

**Issue by iamquan** [willianjusten/cards-jekyll-template#7]
Hi, I did follow your installation instructions to run in local and when I do ```npm install``` then press ```gulp```, it shows error: ```gulp: command not found```. I did try on different machine, the result is the same. May be I'm missing something?

**Comment by willianjusten** [comment]
You should run `npm install -g gulp gulp-cli` to have gulp installed at your machine. 
If you don't want to, you can run using `./node_modules/.bin/gulp`.
